app = 'evolutionapi' 
primary_region = 'Rio de Janeiro, Brazil'    

[build]
  image = "atendai/evolution-api:v1.8.2" 


[[services]]
  protocol = "tcp"
  internal_port = 8080 

  
  [[services.ports]]
    port = 8081 